import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { ClientConfig } from "../../config/schema.js";
import { runEval } from "../../concierge/eval.js";
import { buildContract } from "../../ingestion/ingest.js";
import { resolveSource } from "../../ingestion/source.js";
import { detectRepo } from "../detect.js";
import { buildConfig, renderConfig, slugify, starterEval } from "../render.js";
import { parse } from "yaml";

const fixture = (name: string) => fileURLToPath(new URL(`../../ingestion/test/fixtures/${name}`, import.meta.url));

async function onboard(name: string) {
  const path = fixture(name);
  const proposal = await detectRepo(path);
  const config = buildConfig({ id: slugify(name), name, source: { type: "local", path } }, proposal);
  const { contract } = await buildContract(config, resolveSource(config));
  return { proposal, config, contract };
}

describe("docent init: detecting a repo", () => {
  it("proposes a config for a repo with an inventory, specs, patterns and JSON rules", async () => {
    const { proposal } = await onboard("acme-ds");
    const i = proposal.ingestion;
    expect(i.components[0]!.include).toEqual(["src/components/**/*.tsx"]);
    expect(i.tokens.map((t) => t.extractor)).toEqual(["css-variables", "tailwind-theme"]);
    expect(i.tokens[0]).toMatchObject({ include: ["src/styles/tokens.css"], modes: { ":root": "light", ".dark": "dark" } });
    expect(i.manifest).toMatchObject({ path: "components.json", itemsPath: "components", fields: { id: "key", name: "title", files: "paths", status: "lifecycle", category: "group" } });
    expect(i.specs).toMatchObject({ sourceField: "source", idField: "id", fields: { intent: "intent", forbiddenUsage: "rules.forbiddenUsage", structure: "structure" } });
    expect(i.patterns!.fields).toMatchObject({ id: "id", name: "title", intent: "purpose", requiredComponents: "uses", sequence: "steps", rules: "do", forbidden: "dont" });
    expect(i.governance!.rules[0]).toMatchObject({ include: ["design/rules.json"], itemsPath: "rules", fields: { id: "id", rule: "text", severity: "level", response: "say" } });
    expect(i.governance!.checks).toEqual({
      "restricted-package": "NO_THIRD_PARTY_UI",
      "unindexed-component": "INDEXED_ONLY",
      "raw-color": "NO_RAW_COLORS",
      "palette-utility": "NO_RAW_COLORS",
      "invalid-prop-value": "VALID_PROPS",
      "compound-structure": "PARTS_IN_PARENT",
      "base-mutation": "NO_BASE_EDITS",
    });
    expect(proposal.specialists).toEqual(["components", "tokens", "patterns", "governance"]);
  });

  it("turns what it can't decide into TODOs instead of guessing", async () => {
    const { proposal } = await onboard("acme-ds");
    const todos = proposal.todos.join("\n");
    expect(todos).toContain("Narrow ingestion.components");
    expect(todos).toContain('".brand-sunset"');
    expect(todos).toContain("global CSS entry");
  });

  it("proposes a config for a Tailwind v4 repo with rules in markdown and no patterns", async () => {
    const { proposal } = await onboard("globex-ds");
    const i = proposal.ingestion;
    expect(i.components[0]!.include).toEqual(["src/components/ui/**/*.tsx"]);
    expect(i.tokens[0]).toMatchObject({ extractor: "css-variables", modes: { "@theme": "base", ":root": "base", ".dark": "dark" } });
    expect(i.defaultMode).toBe("base");
    expect(i.governance!.rules).toEqual([expect.objectContaining({ include: ["AGENTS.md"], heading: "Rules of the road", severity: "medium" })]);
    expect(i.governance!.checks).toEqual({ "raw-color": "rules-of-the-road-1", "palette-utility": "rules-of-the-road-1" });
    expect(i.foundation).toMatchObject({ files: ["src/index.css"], packages: ["tailwindcss", "@tailwindcss/vite"] });
    expect(proposal.specialists).toEqual(["components", "tokens", "governance"]);
  });

  it("writes a valid, commented config", async () => {
    const proposal = await detectRepo(fixture("globex-ds"));
    const yaml = renderConfig({ id: "globex", name: "Globex", source: { type: "local", path: fixture("globex-ds") } }, proposal, new Date("2026-09-11"));
    expect(yaml.split("\n")[0]).toBe("# Docent config for Globex, generated by `docent init` on 2026-09-11.");
    expect(yaml).toContain("# TODO before relying on this config:");
    expect(() => ClientConfig.parse(parse(yaml))).not.toThrow();
  });
});

describe("docent onboard: a detected config works end to end", () => {
  it.each(["acme-ds", "globex-ds"])("%s: ingests and passes its starter eval", async (name) => {
    const { config, contract } = await onboard(name);
    expect(contract.stats.components).toBeGreaterThan(0);
    expect(contract.gaps.filter((g) => g.kind === "parse-error" || g.kind === "no-components-found")).toEqual([]);
    const batch = starterEval(contract, config);
    expect(batch.length).toBeGreaterThanOrEqual(5);
    const results = await runEval(contract, config.escalation, batch, "test", config.specialists);
    expect(results.filter((r) => !r.passed).map((r) => `${r.case.name}: ${r.failures.join("; ")}`)).toEqual([]);
  });
});
