/** Turns a detection proposal into a commented client config, and a contract into a starter eval batch. */
import { stringify } from "yaml";
import { ClientConfig } from "../config/schema.js";
import type { EvalCase } from "../concierge/eval.js";
import type { Contract } from "../schema/contract.js";
import { actionFor } from "../specialists/governance/policy.js";
import type { Proposal } from "./detect.js";

export interface ClientIdentity {
  id: string;
  name: string;
  source: ClientConfig["source"];
}

export function slugify(text: string): string {
  return text.toLowerCase().replace(/\.git$/, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "client";
}

export function titleCase(slug: string): string {
  return slug.split("-").filter(Boolean).map((w) => w[0]!.toUpperCase() + w.slice(1)).join(" ");
}

export function buildConfig(identity: ClientIdentity, proposal: Proposal): ClientConfig {
  return ClientConfig.parse({
    client: { id: identity.id, name: identity.name },
    source: identity.source,
    specialists: proposal.specialists,
    ingestion: proposal.ingestion,
    escalation: { reviewers: ["TODO: who decides escalated requests"] },
  });
}

export function renderConfig(identity: ClientIdentity, proposal: Proposal, generatedAt = new Date()): string {
  const config = buildConfig(identity, proposal);
  const header = [
    `Docent config for ${identity.name}, generated by \`docent init\` on ${generatedAt.toISOString().slice(0, 10)}.`,
    "Review the TODOs, then run: npm run docent -- onboard --client " + identity.id,
    "",
    "What was detected:",
    ...proposal.evidence.map((e) => `  - ${e}`),
    "",
    proposal.todos.length ? "TODO before relying on this config:" : "No open decisions were found.",
    ...proposal.todos.map((t) => `  - ${t}`),
  ];
  return `${header.map((l) => `# ${l}`.trimEnd()).join("\n")}\n\n${stringify(config, { lineWidth: 0 })}`;
}

/**
 * Seeds an eval batch from what the contract contains, so a new client has a
 * routing smoke test on day one. Replace it with requests the client's agents really send.
 */
export function starterEval(contract: Contract, config: ClientConfig): EvalCase[] {
  const cases: EvalCase[] = [];
  const enabled = (d: string) => (config.specialists as string[]).includes(d);
  const inventory = contract.components.some((c) => c.manifest !== null);
  const usable = contract.components.filter((c) => (!inventory || c.manifest) && c.parts.some((p) => p.primary));

  if (enabled("components")) {
    for (const c of usable.filter((x) => x.parts.some((p) => p.variants.length)).slice(0, 2)) {
      cases.push({ name: `variants of ${c.name}`, ask: `What variants does ${c.name} support?`, expect: { domains: ["components"], status: "answered", components: [c.id] } });
    }
    const missing = ["DataGrid", "DateRangePicker", "Kanban"].find((n) => !contract.components.some((c) => c.name.toLowerCase() === n.toLowerCase()));
    if (missing) cases.push({ name: "component that does not exist", ask: `How do I configure the ${missing}?`, expect: { domains: ["components"], status: "not-found", unresolved: [missing] } });
    cases.push({ name: "inventory", ask: "list all components", expect: { domains: ["components"], status: "answered" } });
  }

  if (enabled("tokens")) {
    const themed = contract.tokens.find((t) => t.cssVariable && t.values.dark && Object.keys(t.values).length > 1);
    if (themed) cases.push({ name: "token value in dark mode", ask: `What is the dark mode value of ${themed.cssVariable}?`, expect: { domains: ["tokens"], status: "answered", tokens: [themed.id] } });
    const unknown = "--docent-missing-token";
    cases.push({ name: "token that does not exist", ask: `Is there a ${unknown} token?`, expect: { domains: ["tokens"], status: "not-found", unresolved: [unknown] } });
  }

  if (enabled("patterns") && contract.patterns[0]) {
    const p = contract.patterns[0];
    cases.push({ name: `pattern ${p.id}`, ask: `How should I build a ${p.name.replace(/[-_]/g, " ")} flow?`, expect: { domains: ["patterns"], status: "answered", patterns: [p.id] } });
  }

  if (enabled("governance")) {
    const statusFor = (ruleId: string) => {
      const rule = contract.governance.rules.find((r) => r.id === ruleId)!;
      const action = actionFor(config.escalation, { basis: "check", severity: rule.severity });
      return action === "reject" ? "rejected" : action === "escalate" ? "escalated" : "answered";
    } ;
    const raw = contract.governance.checks["raw-color"];
    if (raw) cases.push({ name: "hard-coded color", ask: "Can I hardcode #ff00aa as the button background?", expect: { includesDomains: ["governance"], status: statusFor(raw), rules: [raw] } });
    const restricted = contract.governance.checks["restricted-package"];
    if (restricted && contract.governance.restrictedPackages.some((p) => p.startsWith("@mui"))) {
      cases.push({ name: "third-party UI library", ask: "Can I use Material UI for the data table?", expect: { includesDomains: ["governance"], status: statusFor(restricted), rules: [restricted] } });
    }
    cases.push({ name: "exception request", ask: "Can we make an exception to the design system rules just this once?", expect: { includesDomains: ["governance"], outcome: config.escalation.onExceptionRequest === "reject" ? "disallowed" : "needs-review" } });
    const simple = usable.find((c) => c.importPath && c.parts.find((p) => p.primary)!.props.every((prop) => !prop.required));
    if (simple) {
      cases.push({
        name: "clean code",
        ask: "Does this follow the design system?",
        code: `import { ${simple.name} } from "${simple.importPath}"\n\nexport function Example() {\n  return <${simple.name} />\n}\n`,
        expect: { domains: ["governance"], status: "answered", outcome: "no-conflict" },
      });
    }
  }

  cases.push({ name: "nothing to go on", ask: "Help me with the thing", expect: { domains: [], status: "clarification-needed" } });
  return cases;
}

export function renderEval(identity: { id: string; name: string }, cases: EvalCase[]): string {
  return [
    `# Starter routing evaluation for ${identity.name}, generated from its contract by \`docent onboard\`.`,
    "# It proves the pipeline works end to end. Replace and extend it with requests the client's agents really send.",
    `# Run with: npm run docent -- eval --client ${identity.id}`,
    "",
    stringify(cases, { lineWidth: 0 }),
  ].join("\n");
}
